poster/lib/poster_web/router.ex
defmodule PosterWeb.Router do
  use PosterWeb, :router

  import PosterWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PosterWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_current_user
  end

  scope "/", PosterWeb do
    pipe_through :browser

    live "/author/:id", AuthorLive.Show, :show
    live "/", PostLive.Index, :index
    live "/p/:slug", PostLive.Show, :show
    resources "/posts", PostController, param: "slug", except: [:show, :index]
  end

  # Other scopes may use custom stacks.
  # scope "/api", PosterWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: PosterWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", PosterWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", PosterWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", PosterWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

poster/lib/poster_web/views/layout_view.ex
defmodule PosterWeb.LayoutView do
  use PosterWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

poster/lib/poster_web/templates/layout/_user_menu.html.heex
<ul class="list-reset lg:flex justify-end flex-1 items-center">
<%= if @current_user do %>
  <li><p class="inline-block px-4 text-gray-400"><%= @current_user.author.name %></p></li>
  <li><%= link "Settings", to: Routes.user_settings_path(@conn, :edit),
    class: "inline-block px-4 text-gray-400 hover:text-gray-100" %></li>
  <li
    @click="isOpen = false"
  ><%= live_redirect "Profile", to: Routes.author_show_path(@conn, :show, @current_user.author),
    class: "inline-block px-4 text-gray-400 hover:text-gray-100" %></li>
  <%# TODO: Reduce boilerplate %>
  <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete,
    class: "inline-block px-4 text-gray-400 hover:text-gray-100" %></li>
<% else %>
  <li><%= link "Register", to: Routes.user_registration_path(@conn, :new),
      class: "inline-block px-4 text-gray-400 hover:text-gray-100" %></li>
  <li><%= link "Log in", to: Routes.user_session_path(@conn, :new),
      class: "inline-block px-4 text-gray-400 hover:text-gray-100" %></li>
<% end %>
</ul>

poster/lib/poster_web/templates/layout/app.html.heex
<main>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

poster/lib/poster_web/templates/layout/live.html.heex
<main>
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

poster/lib/poster_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Poster", suffix: " · Poster" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/2.3.10/purify.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.3.5/dist/alpine.min.js"></script>
  </head>
  <body>
    <nav class="flex items-center justify-between flex-wrap bg-gray-800 p-6 fixed w-full z-10 top-0"
         x-data="{ isOpen: false }"
      >
      <div class="flex items-center flex-shrink-0 text-white mr-6">
        <span
          @click="isOpen = false"
        >
          <%= live_redirect "Poster", to: "/", class: "text-2xl pl-2" %>
        </span>
      </div>

      <div class="block lg:hidden">
        <button
          @click="isOpen = !isOpen"
          id="nav-toggle"
          class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-white hover:border-white"
        >
          <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
      </div>

      <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block pt-6 lg:pt-0" id="nav-content"
           :class="{ 'block shadow-3xl': isOpen, 'hidden': !isOpen }"
        >
        <%= render "_user_menu.html", assigns %>
      </div>
    </nav>

    <!--Container-->
    <div class="shadow-lg mx-auto bg-white mt-24 md:mt-18"></div>

    <div class="p-4">
      <%= @inner_content %>
    </div>
  </body>
</html>