poster/lib/poster_web/router.ex
defmodule PosterWeb.Router do
  use PosterWeb, :router

  import PosterWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PosterWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_current_user
  end

  scope "/", PosterWeb do
    pipe_through :browser

    live "/author/:id", AuthorLive.Show, :show
    live "/", PostLive.Index, :index
    live "/p/:slug", PostLive.Show, :show
    resources "/posts", PostController, param: "slug", except: [:show, :index]
  end

  # Other scopes may use custom stacks.
  # scope "/api", PosterWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: PosterWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", PosterWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", PosterWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", PosterWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

poster/lib/poster_web/live/auth_live.ex
defmodule PosterWeb.LiveAuth do
  @moduledoc """
  Helper for handling user authenticated and authorization
  in LiveView routes.
  """

  import Phoenix.LiveView

  alias Poster.Accounts

  def on_mount(:fetch_user, _, session, socket) do
    socket = assign_current_user(socket, session)
    {:cont, socket}
  end

  defp assign_current_user(socket, session) do
    case session do
      %{"user_token" => user_token} ->
        assign_new(socket, :current_user, fn ->
          Accounts.get_user_by_session_token(user_token)
          |> Poster.Repo.preload(:author)
        end)

      %{} ->
        assign_new(socket, :current_user, fn -> nil end)
    end
  end
end

poster/lib/poster_web/live/author_live/show.ex
defmodule PosterWeb.AuthorLive.Show do
  @moduledoc false

  use PosterWeb, :live_view

  alias Poster.Blog

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id} = params, _, socket) do
    author = Blog.get_author!(id)

    page =
      Blog.get_author_posts(author)
      |> Poster.Repo.paginate(params)

    {:noreply,
     socket
     |> assign(:page_title, author_title(author.name))
     |> assign(:author, author)
     |> assign(:page, page)}
  end

  defp author_title(name) do
    "#{name}'s profile'"
  end

  defp get_posts_string(total_posts) do
    case total_posts do
      0 -> "This user has no posts yet"
      1 -> "1 post"
      n -> "#{n} posts"
    end
  end
end

poster/lib/poster_web/live/live_helpers.ex
defmodule PosterWeb.LiveHelpers do
  @moduledoc false

  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.post_index_path(@socket, :index)}>
        <.live_component
          module={PosterWeb.PostLive.FormComponent}
          id={@post.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.post_index_path(@socket, :index)}
          post: @post
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
          <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

poster/lib/poster_web/live/post_live/index.ex
defmodule PosterWeb.PostLive.Index do
  @moduledoc false

  use PosterWeb, :live_view

  @topic "posts"

  alias Poster.Posts

  @impl true
  def mount(params, _session, socket) do
    PosterWeb.Endpoint.subscribe(@topic)
    {:ok, assign(socket, :posts, list_posts(params))}
  end

  @impl true
  def handle_info(%{topic: @topic, payload: post}, socket) do
    post = Poster.Repo.preload(post, [:author, :comments, :tags])

    posts =
      if socket.assigns.page.page_number < 2 do
        [post | socket.assigns.posts]
      else
        socket.assigns.posts
      end

    {:noreply, assign(socket, :posts, posts)}
  end

  @impl true
  def handle_event("search", %{"query" => query}, socket) do
    {:noreply, push_patch(socket, to: Routes.post_index_path(socket, :index, query))}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :index, params) do
    {posts, page} = list_posts(params)

    socket
    |> assign(:page_title, "Browsing Posts")
    |> assign(:posts, posts)
    |> assign(:page, page)
    |> assign(:query, Map.get(params, "query", nil))
    |> assign(:sorter, Map.get(params, "sorter", "New"))
    |> assign(:mode, Map.get(params, "mode", "Descending"))
  end

  defp list_posts(params) do
    page =
      params
      |> extract_search_term()
      |> Posts.list_posts()
      |> Posts.sort_posts(parse_sorting(params))
      |> Poster.Repo.paginate(params)

    posts = Poster.Repo.preload(page.entries, [:author, :tags, :comments])
    {posts, page}
  end

  defp extract_search_term(params) do
    with query <- get_in(params, ["query"]),
         true <- query != "" do
      query
    else
      _ -> nil
    end
  end

  defp parse_sorting(params) do
    sorter =
      case Map.get(params, "sorter") do
        "Recently updated" -> :recently_updated
        "New" -> :new
        _ -> :new
      end

    mode =
      case Map.get(params, "mode") do
        "Ascending" -> :asc
        "Descending" -> :desc
        _ -> :desc
      end

    {sorter, mode}
  end
end

poster/lib/poster_web/live/post_live/show.ex
defmodule PosterWeb.PostLive.Show do
  @moduledoc false

  use PosterWeb, :live_view
  on_mount {PosterWeb.LiveAuth, :fetch_user}

  @topic "comments"

  alias Poster.Posts
  alias Poster.Markdown
  alias Poster.Posts.Comment

  @impl true
  def mount(_params, _session, socket) do
    PosterWeb.Endpoint.subscribe(@topic)

    {:ok,
     assign(socket,
       changeset: Posts.change_comment(%Comment{})
     )}
  end

  @impl true
  def handle_params(%{"slug" => slug} = params, _, socket) do
    post = Posts.get_post_by_slug!(slug, [:tags, :author])
    markdown = Markdown.to_html!(post.body)

    comments_page =
      Posts.post_comments(post)
      |> Poster.Repo.paginate(params)

    comments = Poster.Repo.preload(comments_page.entries, :author)

    {:noreply,
     socket
     |> assign(:page_title, post.title)
     |> assign(:post, post)
     |> assign(:comments, comments)
     |> assign(:page, comments_page)
     |> assign(:rendered_markdown, markdown)}
  end

  @impl true
  def handle_event("validate", %{"comment" => params}, socket) do
    changeset =
      %Comment{}
      |> Posts.change_comment(params)
      |> Map.put(:action, :insert)

    {:noreply, assign(socket, changeset: changeset)}
  end

  @impl true
  def handle_event("save", %{"comment" => params}, socket) do
    post = socket.assigns.post

    comment =
      case socket.assigns.current_user do
        nil -> Posts.create_comment(params, post)
        user -> Posts.create_comment_with_author(params, post, user.author)
      end

    case comment do
      {:ok, comment} ->
        PosterWeb.Endpoint.broadcast_from!(self(), @topic, "new_comment" <> comment.id, comment)

        {:noreply,
         assign(socket,
           comments: [comment | socket.assigns.comments],
           changeset: Posts.change_comment(%Comment{})
         )}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end

  @impl true
  def handle_info(%{topic: @topic, payload: comment}, socket) do
    comment = Poster.Repo.preload(comment, :author)

    comments =
      if socket.assigns.page.page_number < 2 do
        [comment | socket.assigns.comments]
      else
        socket.assigns.comments
      end

    {:noreply, assign(socket, :comments, comments)}
  end

  defp safe_html(html_body) do
    {:safe, sanitized} = sanitize(html_body)
    sanitized
  end

  defp format_post_date(datetime) do
    Timex.format!(datetime, "%Y-%m-%d %H:%M", :strftime)
  end

  defp is_owner?(author, post) do
    post.author_id == author.id
  end

  defp relative_comment_date(time) do
    Timex.format!(time, "{relative}", :relative)
  end
end

poster/lib/poster_web/live/post_live/index.html.heex
<h1 class="text-3xl font-bold">
  Recent Posts
</h1>

<div class="flex flex-wrap mt-2 gap-y-4">
  <%= form_for :query, "#", [phx_change: "search", id: "search-form"], fn f -> %>
    <div class="relative mr-3">
      <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
        <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
      </div>
      <%= search_input f, :query, value: @query, class: "block p-4 pl-10 w-full text-sm text-gray-900 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500", placeholder: "Search for content or tags..." %>
    </div>

    <div class="mt-2 flex gap-x-3">
      <div>
        <%= select f, :sorter, ["New", "Recently updated"], value: @sorter, class: "appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
        <label class="uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-state">
          Sort by
        </label>
      </div>

      <div>
        <%= select f, :mode, ["Descending", "Ascending"], value: @mode,
          class: "appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
        <label class="uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-state">
          Mode
        </label>
      </div>

      <div style="height: 50px">
        <%= link "Create Post", to: Routes.post_path(@socket, :new), type: "button",
          class: "bg-blue-500 h-full flex content-center items-center hover:bg-blue-700 text-white font-bold px-4 mr-4 rounded" %>
      </div>
    </div>
  <% end %>
</div>

<div class="mt-4">
  <h2 class="text-xl mb-2">Total results: <%= @page.total_entries %> </h2>

  <%= if @page.total_pages > 1 do %>
    <nav aria-label="Page navigation" id="pagination-navigation">
      <ul class="inline-flex space-x-2">
        <li>
          <%= live_patch type: "button", to: Routes.post_index_path(@socket, :index, page: @page.page_number - 1), class: "hover:cursor-pointer flex items-center justify-center w-10 h-10 text-blue-600 transition-colors duration-150 bg-white rounded-full focus:shadow-outline hover:bg-blue-100" do %>
            <svg class="w-4 h-4 fill-current" viewBox="0 0 20 20"><path d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" fill-rule="evenodd"></path></svg>
          <% end %>
        </li>

        <li>
          <%= live_patch to: Routes.post_index_path(@socket, :index, page: 1),
            class: SharedView.pagination_button_classes(@page.page_number, 1) do %>
            1
          <% end %>
        </li>

        <%= if @page.page_number > 1 and @page.page_number < @page.total_pages do %>
          <%= content_tag :p, class: SharedView.pagination_button_classes(@page.page_number, @page.page_number) do %>
            <%= @page.page_number %>
          <% end %>
        <% end %>

        <%= if @page.total_pages > 1 do %>
          <li>
            <%= live_patch type: "button", to: Routes.post_index_path(@socket, :index, page: @page.total_pages),
                class: SharedView.pagination_button_classes(@page.page_number, @page.total_pages) do %>
              <%= @page.total_pages %>
            <% end %>
          </li>
        <% end %>

        <%= if @page.page_number != @page.total_pages do %>
          <li>
            <%= live_patch type: "button", to: Routes.post_index_path(@socket, :index, page: @page.page_number + 1), class: "flex items-center justify-center w-10 h-10 text-blue-600 transition-colors duration-150 bg-white rounded-full focus:shadow-outline hover:bg-blue-100" do %>
               <svg class="w-4 h-4 fill-current" viewBox="0 0 20 20"><path d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" fill-rule="evenodd"></path></svg>
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>
  <% end %>
</div>

<%= render(PosterWeb.PostListView, "index.html",
    posts: @posts, conn: @socket, show_author: true) %>

poster/lib/poster_web/live/post_live/show.html.heex
<div class="flex flex-col items-center">
  <div class="md:w-1/3 w-full">
    <article class="prose">
      <h1 class="text-3xl font-bold content-left m-0">
        <%= @post.title %>
      </h1>

      <div class="flex">
        <%= if assigns.current_user && is_owner?(assigns.current_user.author, @post) do %>
          <span><%= link "Edit", to: Routes.post_path(@socket, :edit, @post.slug),
            class: "no-underline bg-blue-500 flex content-center items-center hover:bg-blue-700 text-white font-bold px-4 mr-4 rounded my-2" %></span>
          <span><%= link "Delete", to: Routes.post_path(@socket, :delete, @post.slug), method: :delete,
            class: "no-underline bg-red-500 flex content-center items-center hover:bg-red-700 text-white font-bold px-4 mr-4 rounded my-2"%></span>
        <% end %>
      </div>

      <div>
        <%= if @post.author != nil do %>
          <p>Written by: <%= live_redirect SharedView.author_name(@post),
            to: Routes.author_show_path(@socket, :show, @post.author),
            class: "no-underline text-blue-700 hover:underline" %></p>
        <% else %>
          <p>Written by: Anonymous</p>
        <% end %>
        <p>Tags: <%=  SharedView.render_tags(@post.tags) %></p>
        <p>Published at: <%= format_post_date(@post.inserted_at) %></p>

        <%= if @post.updated_at > @post.inserted_at do %>
          <p>Last update: <%= format_post_date(@post.updated_at) %></p>
        <% end %>
      </div>
      <hr class="m-0" />
      <div>
        <%= raw(safe_html(@rendered_markdown)) %>
      </div>
    </article>

    <div class="flex flex-col">
      <div class="content-start w-96">
         <h1 class="text-2xl font-bold mb-2">
           Comments
         </h1>

         <%= if @page.total_pages > 1 do %>
           <nav aria-label="page navigation" id="pagination-navigation" class="pb-2">
             <ul class="inline-flex space-x-2">
               <li>
                 <%= live_patch type: "button", to: Routes.post_show_path(@socket, :show, @post.slug, page: @page.page_number - 1), class: "hover:cursor-pointer flex items-center justify-center w-10 h-10 text-blue-600 transition-colors duration-150 bg-white rounded-full focus:shadow-outline hover:bg-blue-100" do %>
                   <svg class="w-4 h-4 fill-current" viewBox="0 0 20 20"><path d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" fill-rule="evenodd"></path></svg>
                 <% end %>
               </li>

               <li>
                 <%= live_patch to: Routes.post_show_path(@socket, :show, @post.slug, page: 1),
                    class: SharedView.pagination_button_classes(@page.page_number, 1) do %>
                   1
                 <% end %>
               </li>

               <%= if @page.page_number > 1 and @page.page_number < @page.total_pages do %>
                 <%= content_tag :p, class: SharedView.pagination_button_classes(@page.page_number, @page.page_number) do %>
                   <%= @page.page_number %>
                 <% end %>
               <% end %>

               <%= if @page.total_pages > 1 do %>
                 <li>
                   <%= live_patch type: "button", to: Routes.post_show_path(@socket, :show, @post.slug, page: @page.total_pages),
                       class: SharedView.pagination_button_classes(@page.page_number, @page.total_pages) do %>
                     <%= @page.total_pages %>
                   <% end %>
                 </li>
               <% end %>

               <%= if @page.page_number != @page.total_pages do %>
                 <li>
                   <%= live_patch type: "button", to: Routes.post_show_path(@socket, :show, @post.slug, page: @page.page_number + 1), class: "flex items-center justify-center w-10 h-10 text-blue-600 transition-colors duration-150 bg-white rounded-full focus:shadow-outline hover:bg-blue-100" do %>
                      <svg class="w-4 h-4 fill-current" viewBox="0 0 20 20"><path d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" fill-rule="evenodd"></path></svg>
                   <% end %>
                 </li>
               <% end %>
             </ul>
           </nav>
         <% end %>

        <.form let={f} id="comment-form" for={@changeset} phx-change="validate" phx-submit="save">
            <%= textarea f, :body, maxlength: 240, placeholder: "Write a commentary...", cols: 40,
              class: "h-32 text-sm text-gray-900 border-gray-300 rounded-lg border focus:ring-blue-500 focus:border-blue-500" %>
            <%= error_tag f, :body %>

            <%= submit "Save", class: "bg-blue-500 flex content-center items-center hover:bg-blue-700 text-white font-bold px-4 mr-4 rounded my-2" %>
        </.form>

        <div id="comments" class="content-start">
          <%= for comment <- @comments do %>
            <div class="my-2">
              <h2 class="text-xl">Author: <%= SharedView.author_name(comment) %></h2>
              <p><%= relative_comment_date(comment.inserted_at) %></p>
              <p><%= comment.body %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<p id="post-id" class="hidden"><%= @post.id %></p>

<script>
  window.addEventListener('DOMContentLoaded', (event) => {
    const comments = document.getElementById('comments')
    autoAnimate(comments);
  });
</script>